#@ load("@ytt:data", "data")
resource_types:
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:
- name: schedule
  type: time
  source:
    interval: 24h
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

- name: automation-repo
  type: git
  source:
    uri: ((automation_git.url))
    branch: ((automation_git.branch))
    username: ((git.username))
    password: ((git.token))

- name: locks
  type: pool
  source:
    pool: ((lock_folder))
    uri: ((locks_git.url))
    branch: ((locks_git.branch))
    username: ((git.username))
    password: ((git.token))
    retry_delay: 60s

- name: email
  type: email
  source:
    from: ((smtp.from_address))
    to: [((smtp.to_addresses))]
    smtp:
      host: ((smtp.address))
      port: ((smtp.port))
      #@ if data.values.smtp.is_auth_required == True:
      username: ((smtp.username))
      password: ((smtp.password))
      #@ else:
      anonymous: true
      #@ end

- name: tile-config-convertor
  type: github-release
  source:
    user: rahulkj
    repository: tile-config-convertor
    access_token: ((git.token))

- name: custom-docker-image
  type: docker-image
  source:
    repository: rjain/buildbox

#@ for product in data.values.products:
#@ if product.metadata.deploy_product == True:
- name: #@ product.name + "-git-repo"
  type: git
  source:
    uri: ((config_repo_git.url))
    branch: ((config_repo_git.branch))
    username: ((git.username))
    password: ((git.token))
    paths:
    - #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
    - #@ "((" + product.name + "_vars_path))/((" + product.name + "_var_filename))"
    - ((opsman_env.path))/((opsman_env.filename))

- name: #@ product.name
  type: s3
  source:
    endpoint: ((s3.endpoint))
    access_key_id: ((s3.access_key))
    secret_access_key: ((s3.secret_key))
    disable_ssl: ((s3.disable_ssl))
    bucket: #@ product.s3.bucket
    regexp: #@ product.s3.product_regex

#@ if/end product.metadata.has_stemcell == True:
- name: #@ product.name + "-stemcells"
  type: s3
  source:
    endpoint: ((s3.endpoint))
    access_key_id: ((s3.access_key))
    secret_access_key: ((s3.secret_key))
    disable_ssl: ((s3.disable_ssl))
    bucket: #@ product.s3.stemcell_bucket
    regexp: #@ "bosh-stemcell-(" + product.pivnet.stemcell_version + ".*)-" + data.values.iaas + "-esxi-ubuntu-xenial-go_agent.tgz"
#@ end

#@ if product.metadata.is_platform_automation == True:
- name: #@ product.name
  type: s3
  source:
    endpoint: ((s3.endpoint))
    bucket: #@ product.s3.bucket
    regexp: #@ product.s3.product_regex
    access_key_id: ((s3.access_key))
    secret_access_key: ((s3.secret_key))
    disable_ssl: true
#@ end
#@ end

groups:
- name: all
  jobs:
  - scheduler
  - unset-lock
  #@ for product in data.values.products:
  #@ if product.metadata.deploy_product == True:
  #@ if data.values.separate_config == True:
  - #@ "lock-upload-stage-" + product.name
  - #@ "configure-deploy-unlock-" + product.name
  #@ else:
  - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
  #@ end
  - #@ "generate-config-" + product.name
  #@ end
  #@ end
#@ for product in data.values.products:
#@ if product.metadata.deploy_product == True:
- name: #@ product.name
  jobs:
  #@ if data.values.separate_config == True:
  - #@ "lock-upload-stage-" + product.name
  - #@ "configure-deploy-unlock-" + product.name
  #@ else:
  - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
  #@ end
  - #@ "generate-config-" + product.name
#@ end
#@ end

jobs:
- name: scheduler
  plan:
  - get: schedule
    trigger: true

#@ deploy_product_index=-1
#@ for product in data.values.products:
#@ if product.metadata.deploy_product == True:
#@ if deploy_product_index != -1:
#@  product_prev=data.values.products[deploy_product_index]
#@ end
#@ if data.values.separate_config == True:
#@   job_name="lock-upload-stage-"
#@   config_job_name="configure-deploy-unlock-"
#@ else:
#@   job_name="lock-upload-stage-configure-deploy-unlock-"
#@   config_job_name="lock-upload-stage-configure-deploy-unlock-"
#@ end
- name: #@ job_name + product.name
  serial: true
  plan:
  - in_parallel:
    - get: schedule
      #@ if deploy_product_index != -1:
      passed:
      - #@ config_job_name + product_prev.name
      #@ else:
      passed:
      - scheduler
      #@ end
    - get: automation-repo
    - get: config-repo
      resource: #@ product.name + "-git-repo"
      trigger: true
    - get: platform-automation-image
      params:
        unpack: true
        globs: ["*.tgz"]
    - get: platform-automation-tasks
      params:
        unpack: true
        globs: ["*.zip"]
    - get: product
      resource: #@ product.name
      trigger: true
    #@ if/end product.metadata.has_stemcell == True:
    - get: stemcells
      resource: #@ product.name + "-stemcells"
      trigger: true
    - put: locks
      params: {acquire: true}
      get_params:
        depth: 30

  - task: create-opsman-env-file
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: config-repo
    output_mapping:
      interpolated-files: env
    params:
      PREFIX: ((credhub.prefix))
      CREDHUB_CA_CERT: ((credhub.ca_cert))
      CREDHUB_CLIENT: ((credhub.client))
      CREDHUB_SECRET: ((credhub.client_secret))
      CREDHUB_SERVER: ((credhub.server))
      INTERPOLATION_PATHS: ((opsman_env.path))

  - in_parallel:
    - task: upload-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-product.yml
      input_mapping:
        product: product
        env: env
      params:
        ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
      on_failure:
        put: locks
        params: {release: locks}
        get_params:
          depth: 30

    #@ if/end product.metadata.has_stemcell == True:
    - task: upload-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        stemcell: stemcells
        env: env
      params:
        ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
      on_failure:
        put: locks
        params: {release: locks}
        get_params:
          depth: 30

  - task: stage-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/stage-product.yml
    input_mapping:
      product: product
      env: env
    params:
      ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

#@ if data.values.separate_config == True:
  - put: locks
    params: {release: locks}
    get_params:
      depth: 30
#@ end

#@ if data.values.separate_config != True:
  - task: create-product-var-files
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: config-repo
    output_mapping:
      interpolated-files: vars
    params:
      PREFIX: ((credhub.prefix))
      CREDHUB_CA_CERT: ((credhub.ca_cert))
      CREDHUB_CLIENT: ((credhub.client))
      CREDHUB_SECRET: ((credhub.client_secret))
      CREDHUB_SERVER: ((credhub.server))
      INTERPOLATION_PATHS: #@ "((" + product.name + "_vars_path))"
      SKIP_MISSING: true
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: config-repo
      env: env
      vars: vars
    params:
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
      ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
      VARS_FILES: #@ "((vars_folder))/((" + product.name + "_vars_path))/((" + product.name + "_var_filename))"
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

  - task: deploy-product
    image: platform-automation-image
    file: automation-repo/tasks/apply-product-changes.yml
    input_mapping:
      env: env
      config: config-repo
    params:
      ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
    attempts: ((apply_changes_attempts))
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

  - put: locks
    params: {release: locks}
    get_params:
      depth: 30

  - put: email
    params:
      subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}"
      body_text: "Build finished: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
#@ deploy_product_index=data.values.products.index(product)
#@ end
#@ end
#@ end

#@ for product in data.values.products:
#@ if product.metadata.deploy_product == True:
#@ if data.values.separate_config == True:
- name: #@ "configure-deploy-unlock-" + product.name
  serial: true
  plan:
  - in_parallel:
    - get: locks
      params:
        depth: 30
    - get: config-repo
      resource: #@ product.name + "-git-repo"
      trigger: true
    - get: automation-repo
    - get: platform-automation-image
      params:
        unpack: true
        globs: ["*.tgz"]
    - get: platform-automation-tasks
      params:
        unpack: true
        globs: ["*.zip"]
    - get: schedule
      passed:
      - #@ "lock-upload-stage-" + product.name
    - get: product
      resource: #@ product.name
      passed:
      - #@ "lock-upload-stage-" + product.name
      trigger: true
    #@ if/end product.metadata.has_stemcell == True:
    - get: stemcells
      resource: #@ product.name + "-stemcells"
      passed:
      - #@ "lock-upload-stage-" + product.name
      trigger: true
      params:
        skip_download: "true"

    - put: locks
      params: {acquire: true}
      get_params:
        depth: 30

  - task: create-opsman-env-file
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: config-repo
    output_mapping:
      interpolated-files: env
    params:
      PREFIX: ((credhub.prefix))
      CREDHUB_CA_CERT: ((credhub.ca_cert))
      CREDHUB_CLIENT: ((credhub.client))
      CREDHUB_SECRET: ((credhub.client_secret))
      CREDHUB_SERVER: ((credhub.server))
      INTERPOLATION_PATHS: ((opsman_env.path))
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

  - task: create-product-var-files
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: config-repo
    output_mapping:
      interpolated-files: vars
    params:
      PREFIX: ((credhub.prefix))
      CREDHUB_CA_CERT: ((credhub.ca_cert))
      CREDHUB_CLIENT: ((credhub.client))
      CREDHUB_SECRET: ((credhub.client_secret))
      CREDHUB_SERVER: ((credhub.server))
      INTERPOLATION_PATHS: #@ "((" + product.name + "_vars_path))"
      SKIP_MISSING: true
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: config-repo
      env: env
      vars: vars
    params:
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
      ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
      VARS_FILES: #@ "((vars_folder))/((" + product.name + "_vars_path))/((" + product.name + "_var_filename))"
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

  - task: deploy-product
    image: platform-automation-image
    file: automation-repo/tasks/apply-product-changes.yml
    input_mapping:
      env: env
      config: config-repo
    params:
      ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
    attempts: ((apply_changes_attempts))
    on_failure:
      put: locks
      params: {release: locks}
      get_params:
        depth: 30

  - put: locks
    params: {release: locks}
    get_params:
        depth: 30

  - put: email
    params:
      subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}"
      body_text: "Build finished: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
#@ end
#@ end
#@ end

#@ for product in data.values.products:
#@ if product.metadata.deploy_product == True:
- name: #@ "generate-config-" + product.name
  serial: true
  plan:
  - in_parallel:
    - get: automation-repo
    - get: config-repo
      resource: #@ product.name + "-git-repo"
    - get: tile-config-convertor
      params:
        globs:
        - "*linux*64"
    - get: custom-docker-image
    - get: platform-automation-image
      params:
        unpack: true
        globs: ["*.tgz"]
    - get: platform-automation-tasks
      params:
        unpack: true
        globs: ["*.zip"]
    - get: product
      resource: #@ product.name
      trigger: true
      params:
        skip_download: "true"
      #@ if data.values.separate_config == True:
      passed:
      - #@ "lock-upload-stage-" + product.name
      #@ else:
      passed:
      - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
      #@ end
    #@ if product.metadata.has_stemcell == True:
    - get: #@ product.name + "-stemcells"
      #@ if data.values.separate_config == True:
      passed:
      - #@ "lock-upload-stage-" + product.name
      #@ else:
      passed:
      - #@ "lock-upload-stage-configure-deploy-unlock-" + product.name
      #@ end
      params:
        skip_download: "true"
    #@ end

  - task: create-opsman-env-file
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: config-repo
    output_mapping:
      interpolated-files: env
    params:
      PREFIX: ((credhub.prefix))
      CREDHUB_CA_CERT: ((credhub.ca_cert))
      CREDHUB_CLIENT: ((credhub.client))
      CREDHUB_SECRET: ((credhub.client_secret))
      CREDHUB_SERVER: ((credhub.server))
      INTERPOLATION_PATHS: ((opsman_env.path))

  - task: generate-config
    image: custom-docker-image
    file: automation-repo/tasks/generate-config/task.yml
    input_mapping:
      git-repo: automation-repo
      env: env
      config: config-repo
    params:
      ENV_FILE: ((opsman_env.path))/((opsman_env.filename))
      CONFIG_FILE: #@ "((" + product.name + "_config_path))/((" + product.name + "_config_filename))"
#@ end
#@ end

- name: unset-lock
  plan:
  - get: locks
    params:
      depth: 30
  - put: locks
    params: {release: locks}
    get_params:
        depth: 30
